config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships, only: [:new, :create, :destroy]
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]

  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  resources :memberships do
    post 'toggle_confirmation', on: :member
  end

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  include AverageRating

  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user


  def year_date_cannot_be_in_the_future
    if self.founded > Date.today.year
      errors.add(:founded, "Can not be established in the future")
    end
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_admin, only: [:destroy]



  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.user = current_user
    @membership.beer_club = @beer_club
    @memberships_confirmed = Membership.confirmed
    @memberships_unconfirmed = Membership.unconfirmed
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
    if current_user && current_user.authenticate(params[:password])
    end
  end
  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        current_user.memberships.create beer_club_id:@beer_club.id, user_id:current_user.id, confirmed:true
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    if current_user.admin
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(@beer_club) do |f| %>
<% if @beer_club.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

  <ul>
    <% @beer_club.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :founded %><br>
  <%= f.text_field :founded %>
</div>
<div class="field">
  <%= f.label :city %><br>
  <%= f.text_field :city %>
</div>
<br>
<br>
<div class="btn btn-primary">
  <%= f.submit%>
</div>
<% end %>

app/views/beer_clubs/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Edit Beer Club</h1>

<%= render 'form' %>
<div class="btn btn-primary">
  <%= link_to 'Show', @beer_club%>
  <%= link_to 'Back', beer_clubs_path%>
</div>

app/views/beer_clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beer Clubs</h1>
<h2>Number of Beer Clubs: <%=@beer_clubs.count%></h2>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th>Members</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
    <tr>
      <td><%= link_to beer_club.name.capitalize, beer_club_path(beer_club) %></td>
      <td><%= beer_club.founded %></td>
      <td><%= beer_club.city.capitalize %></td>
      <td><%= beer_club.memberships.count%></td>
      <% if current_user %>
      <% unless beer_club.memberships.each {|m| m.user = current_user}%>
      <td><%= link_to 'Join Club', new_membership_path%></td>
      <% end %>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
  <% if current_user%>
  <div class="btn btn-default">
  <%= link_to 'Create Beer Club', new_beer_club_path%>
  <div class="btn btn-default">
  <% else %>
  <h2>Sign in to add Beer Clubs!</h2>
  <br>
  <div class="btn btn-default">
  <%= link_to 'Sign in', signin_path%>
  <% end %>
</div>

app/views/beer_clubs/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New Beer Club</h1>

<%= render 'form' %>
<br>
<div class="btn btn-primary">
  <%= link_to 'Beer Clubs', beer_clubs_path%>
</div>

app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <%= @beer_club.name.capitalize %>
</h1>
<div class="info">
  <h2>
    Founded:
    <%= @beer_club.founded %>
  </h2>

  <h2>
    City:
    <%= @beer_club.city.capitalize %>
  </h2>

  <h2>
    Members:
    <%= @beer_club.memberships.confirmed.count %>
  </h2>
</div>
<br>
<% if @beer_club.memberships.confirmed.count >0%>
<table  class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th>Joined club</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_club.memberships.each do |membership| %>
    <% if membership.confirmed%>
    <tr>
      <td><%= link_to membership.user.username.capitalize, membership.user%></td>
      <td><%= membership.created_at.year%> - <%=membership.created_at.month%> - <%= membership.created_at.day%> - </td>
    </tr>
    <%end%>
    <%end%>
  </tbody>
</table>
  <%end%>

  <%if @beer_club.memberships.unconfirmed.count >0%>
  <h2>Pending Applications</h2>
  <table  class="table table-hover">
    <thead>
      <tr>
        <th>Username</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @beer_club.memberships.unconfirmed.each do |membership| %>
      <% unless membership.confirmed%>
      <tr>
        <td><%= link_to membership.user.username, user_path(membership.user_id)%></td>
        <% if current_user and if current_user.id == membership.user_id and if membership.confirmed?%>
        <td>
          <div class="btn btn-warning">
            <%= link_to 'Leave Club', membership, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
        <%end%>
        <% if current_user and current_user.memberships.confirmed.find_by(beer_club: @beer_club.id) %>
        <%= link_to "Activate Membership", toggle_confirmation_membership_path(membership.id), method: :post, class: "btn btn-xs btn-default" %>
        <%end%>
      </tr>
      <%end%>
      <%end%>
      <%end%>
    </tbody>
  </table>

  <br>
  <%end%>
<br>
<%end%>

<div class="btn btn-primary">
  <% if current_user and if not current_user.memberships.map {|m| m.beer_club.id}.include? @beer_club.id%>
  <%= form_for(@membership) do |f| %>
  <%= f.hidden_field :beer_club_id %>
  <%= f.submit value:"Join The Club"%>
  <% end %>
  <% end %>
  <% end %>
  <br><br>
  <%= link_to 'Back', beer_clubs_path %>
</div>
<% if current_user && current_user.admin  %>
<div class="btn btn-warning">
  <%= link_to 'Delete', @beer_club, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<%end %>