config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships, only: [:new, :create, :destroy]
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]

  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  resources :memberships do
    post 'toggle_confirmation', on: :member
  end

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
	include AverageRating

	validates :name, length: {minimum: 3}
	validates :year, numericality: { greater_than_or_equal_to: 1042,
		only_integer: true}
		validate :year_date_cannot_be_in_the_future

		scope :active, -> { where active:true }
		scope :retired, -> { where active:[nil,false] }

		has_many :beers, dependent: :destroy
		has_many :ratings, through: :beers

		def year_date_cannot_be_in_the_future
			if self.year > Date.today.year
				errors.add(:year, "Can not be established in the future")
			end
		end

		def print_report
			puts name
			puts "established at year #{year}"
			puts "number of beers #{beer.count}"
		end

		def self.top(n)
			sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.AverageRating||0) }
			sorted_by_rating_in_desc_order.first(n)
		end
		#self.ratings.map{|n| n.score}.inject(:+).to_f/self.ratings.count

		def restart
			self.year = 2017
			puts "changed year to #{year}"
		end

		def to_s
			"#{name}, established: #{year}"
		end
	end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :ensure_that_admin, only: [:destroy]
  before_action :skip_if_cached, only:[:index]


  # GET /breweries
  # GET /breweries.json
  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if request.format.html? and fragment_exist?( "brewerylist-#{@order}"  )
  end

  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    @breweries = Brewery.all

    @order = params[:order] || 'name'

    @active_breweries = case @order
    when 'name' then @active_breweries.sort_by{ |b| b.name }
    when 'year' then @active_breweries.sort_by{ |b| b.year }
    end

    @retired_breweries = case @order
    when 'name' then @retired_breweries.sort_by{ |b| b.name }
    when 'year' then @retired_breweries.sort_by{ |b| b.year }
    end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  def list
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  def toggle_activity
    expire_fragment('brewerylist')
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire_fragment('brewerylist')
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire_fragment('brewerylist')
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    expire_fragment('brewerylist')
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end

  def secret_page
    @time = Time.now
  end

end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
  <%= f.label :active %>
  <%= f.check_box :active %>
</div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th> <%= link_to 'Name', breweries_path(order:"name") %> </th>
    <th><%= link_to 'Year', breweries_path(order:"year") %></th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Edit Brewery</h1>

<%= render 'form' %>

<div class="btn btn-default">
  <%= link_to 'Back', breweries_path %>
</div>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breweries</h1>
<% cache 'brewerylist', skip_digest: true do %>
<h2> Number of Active Breweries: <%= @active_breweries.count %> </h2>

<% unless @active_breweries.nil?%>
<%= render 'list', breweries: @active_breweries %>
<%end%>

<h2> Number of Retired Breweries: <%= @retired_breweries.count %> </h2>

<% unless @retired_breweries.nil?%>
<%= render 'list', breweries: @retired_breweries %>
<%end%>
<%end%>

<br>

<% if current_user%>
<div class="btn btn-default">
  <%= link_to 'Create Brewery', new_brewery_path%>
</div>
<% else %>
<h2>Sign in to add Breweries!</h2>
<br>
<div class="btn btn-default">
  <%= link_to 'Sign in', signin_path%>
  <% end %>
</div>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <div class="btn btn-primary">
    <a href="#" id="reverse">Reverse!</a>
  </div>
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="year">Year</a> </th>
    <th> <a href="#" id="beers"># of Beers</a> </th>
    <th> <p>Active</p> </th>
  </tr>

</table>

app/views/breweries/new.html.erb
<p id="notice"><%= notice %></p>
<h1>Create new Brewery</h1>

<%= render 'form' %>

<div class="btn btn-default">
  <%= link_to 'Back', breweries_path %>
</div>

app/views/breweries/panimot.html.erb
Breweries: <%= @breweries.count %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @brewery.name %>
</h1>
<% unless @brewery.active  %>
  <span class="label label-info">retired</span>
<% end %>
<div class="info">
  <h2>
    Established in: <%= @brewery.year %>
  </h2>

  <h2>
    Number of beers: <%= @brewery.beers.count %>
  </h2>
  <% if @brewery.ratings.empty? %>
  <h2>
    Brewery has not yet been rated!
  </h2>
  <% else %>
  <h2>
    Has <%=@brewery.ratings.count%> <%="rating".pluralize(@brewery.ratings.count)%> with average of <%=@brewery.AverageRating%>
  </h2>
  <% end %>
</div>
<br><br>

<% if @brewery.beers.count >0%>
<table>
  <thead>
    <tr>
      <th>Beer</th>
      <th>Style</th>
      <th>Average rating</th>
      <th>Number of ratings</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @brewery.beers.each do |beer| %>
    <tr>
      <td><%= link_to beer.name.capitalize, beer%></td>
      <td><%= beer.style.name.capitalize %></td>
      <td><%= beer.AverageRating%></td>
      <td><%= beer.ratings.count%></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br><br>
<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
<% if current_user && current_user.admin  %>
<div class="btn btn-warning">
  <%= link_to 'Delete', @brewery, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<%end %>