config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships, only: [:new, :create, :destroy]
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]

  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  resources :memberships do
    post 'toggle_confirmation', on: :member
  end

end

app/models/beer.rb
class Beer < ActiveRecord::Base
	include AverageRating

	validates :name, presence: true,
									length: {minimum: 3}
  validates :style_id, presence: true

	belongs_to :brewery
	belongs_to :style
	has_many :ratings, dependent: :destroy
	has_many :raters, -> { uniq }, through: :ratings, source: :user
	def to_s
		"#{name}: #{brewery.name}"
	end

	def self.top(n)
		sorted_by_rating_in_desc_order = Beer.all.sort_by{ |b| -(b.AverageRating||0) }
		sorted_by_rating_in_desc_order.first(n)
	end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  before_action :set_breweries_and_styles_for_template, only: [:new, :edit, :create]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :ensure_that_admin, only: [:destroy]
  before_action :skip_if_cached, only:[:index]

  # GET /beers
  # GET /beers.json

  def list
  end

  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if request.format.html? and fragment_exist? ("beerlist-#{@order}")
  end

  def index
    @beers = Beer.includes(:brewery, :style).all

    @order = params[:order] || 'name'

    @beers = case @order
    when 'name' then
      @beers.sort_by { |b| b.name }
    when 'brewery' then
      @beers.sort_by { |b| b.brewery.name }
    when 'style' then
      @beers.sort_by { |b| b.style.name }
    end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @rating = Rating.new
    @rating.beer = @beer
  end

  # GET /beers/new
  def new
    @beer = Beer.new
    set_breweries_and_styles_for_template
  end

  # GET /beers/1/edit
  def edit
    expire_fragments
    set_breweries_and_styles_for_template
  end

  def brewery_name
    brewery.name
  end

  # POST /beers
  # POST /beers.json
  def create
    expire_fragments
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beers_path, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_breweries_and_styles_for_template
    @breweries = Brewery.all
    @styles = Style.all
  end
  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    expire_fragments
    if user && user.authenticate(params[:password])
      respond_to do |format|
        if @beer.update(beer_params)
          format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
          format.json { render :show, status: :ok, location: @beer }
        else
          format.html { render :edit }
          format.json { render json: @beer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    expire_fragments
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_beer
    @beer = Beer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_params
    params.require(:beer).permit(:name, :style_id, :brewery_id)
  end

  def expire_fragments
      ["beerlist-name", "beerlist-brewery", "beerlist-style"].each{ |f| expire_fragment(f) }
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(@beer) do |f| %>
<% if @beer.errors.any?%>
<div id="error_explanation">
  <h2><%=pluralize(@beer.errors.count, "error") %> prohibited rating from being saved: </h2>
  <ul>
    <% @beer.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<h2>Name</h2><br> <%=f.text_field :name%><br>
<h2>Brewery</h2><br> <%= f.select :brewery_id, options_from_collection_for_select(@breweries, :id, :to_s)%><br>
<h2>Style</h2><br> <%= f.select :style_id, options_from_collection_for_select(@styles, :id, :name)%>

<br>
<br>
<%= f.submit%>
<% end %>
<br>

app/views/beers/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Edit Beer</h1>

<%= render 'form' %>
<br>
<div class="btn btn-default">
  <%= link_to 'Back', beers_path %>
</div>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beers</h1>

<% cache 'beerlist', skip_digest: true do %>
<h2>Number of Beers: <%=@beers.count%></h2>
<body>
  <% unless @beers.nil?%>
  <div class="tables">
    <table class="table table-hover">
      <thead>
        <tr>
          <th> <%= link_to 'Name', beers_path(order:"name") %> </th>
          <th> <%= link_to 'Style', beers_path(order:"style") %> </th>
          <th> <%= link_to 'Brewery', beers_path(order:"brewery") %> </th>
        </tr>
      </thead>

      <tbody>
        <% @beers.each do |beer| %>
        <tr>
          <td><%= link_to beer.name.capitalize, beer %></td>
          <td><%= beer.AverageRating%></td>
          <td><%= link_to beer.brewery.name.capitalize, brewery_path(beer.brewery_id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>


  <%end%>
  <%end%>
  <br>
  <% if current_user%>
  <div class="btn btn-default">
    <%= link_to 'Create Beer', new_beer_path%>
  </div>
  <% else %>
  <h2>Sign in to add Beers!</h2>
  <br>
  <div class="btn btn-default">
    <%= link_to 'Sign in', signin_path%>
    <% end %>
  </div>

app/views/beers/list.html.erb
<h2>Beers</h2>

<table id="beertable" class="table table-hover">
  <div class="btn btn-primary">
    <a href="#" id="reverse">Reverse!</a>
  </div>
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="style">Style</a> </th>
    <th> <a href="#" id="brewery">Brewery</a> </th>
  </tr>

</table>

app/views/beers/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New Beer</h1>

<%= render 'form' %>
<br>
<div class="btn btn-default">
  <%= link_to 'Back', beers_path %>
</div>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @beer.name %>
</h1>
<div class="info">
  <h2>
    Style: <%= link_to @beer.style.name, @beer.style %>
  </h2>

  <h2>
    Brewery: <%= link_to @beer.brewery.name, @beer.brewery %>
  </h2>
</div>

<% if @beer.ratings.count >0%>
<h1>Ratings</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Score</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @beer.ratings.each do |rating| %>
    <tr>
      <td><%= link_to rating.user.username, user_path(rating.user.id)%></td>
      <td><%= rating.score %></td>
      <td><%= rating.created_at.year%> - <%=rating.created_at.month%> - <%=rating.created_at.day%></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<% if current_user%>
<div class="btn btn-default">
  <%= form_for(@rating) do |f| %>
    <%= f.hidden_field :beer_id %>
    score: <%= f.number_field :score %>
    <br>
    <br>
    <%= f.submit %>
  <% end %>
</div>

<% if current_user && current_user.admin  %>
<div class="btn btn-warning">
  <%= link_to 'Delete', @beer, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<%end %>
<% end %>